variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:5.2.1'
  - &platforms 'linux/arm64'
  - &repositories ['git.jcm.re/jcm/vulkanbot', 'ghcr.io/jncrmx/vulkanbot']
  - publish_logins: &publish_logins
      - registry: https://git.jcm.re
        username:
          from_secret: gitea_package_user
        password:
          from_secret: gitea_package_token
      - registry: https://ghcr.io
        username:
          from_secret: ghcr_user
        password:
          from_secret: ghcr_token

when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  docker:
    image: *buildx_plugin
    settings:
      repo: *repositories
      dockerfile: Dockerfile
      platforms: *platforms
      tag: ["latest", "${CI_COMMIT_SHA}", "${CI_COMMIT_SHA:0:10}"]
      logins: *publish_logins
